#!/bin/sh
set -e


#def apt_get_download(package, dest):
#    dead_code
#    """
#    package name
#    dest filepath
#    """
#    tempdir = tempfile.mkdtemp()
#    try:
#        os.makedirs(os.path.join(tempdir, "state", "lists", "partial"))
#        os.makedirs(os.path.join(tempdir, "cache", "archives", "partial"))
#        open(os.path.join(tempdir, "state", "status"), "w").close()
#        shutil.copyfile("/etc/apt/sources.list",
#                        os.path.join(tempdir, "sources.list"))
#        config_filepath = os.path.join(tempdir, "apt.conf")
#        open(config_filepath, "w").write("""
#Dir::Etc::SourceList "%(tempdir)s/sources.list";
#Dir::State "%(tempdir)s/state";
#Dir::State::status "status";
#Dir::Cache "%(tempdir)s/cache";
#//Dir::Bin::dpkg-source "/bin/true";
#""" % locals())
#        call(["apt-get", "-c", config_filepath, "update"])
#        call(["apt-get", "-c", config_filepath, "install", "-d", "-y", "-m", package])
#        shutil.copyfile(glob.glob(os.path.join(tempdir, "cache", "archives",
#                                               "%s*.deb" % package))[0],
#                        dest)
#    finally:
#        distutils.dir_util.remove_tree(tempdir)



setup_apt()
{
    local aptdir="$1"
    local mirror="$2"
    local distro="$3"
    local component="$4"
    local aptconf="$aptdir/apt.conf"
    mkdir -p "$aptdir"
    cat > "$aptconf" <<EOF
Dir::Etc::SourceList "$aptdir/sources.list";
Dir::State "$aptdir/state";
Dir::State::status "status";
Dir::Cache "$aptdir/cache";
//Dir::Bin::dpkg-source "/bin/true";
EOF
    mkdir -p "$aptdir/state/lists/partial"
    touch "$aptdir/state/status"
    mkdir -p "$aptdir/cache/archives/partial"
    
    cat > "$aptdir/sources.list" <<EOF
deb-src $mirror $distro $component
EOF
}


if [ $# -lt 4 ]; then
    echo "Usage: $0 mirror distro component package" 1>&2
    exit 1 
fi
MIRROR="$1"
DISTRO="$2"
COMPONENT="$3"
PACKAGE="$4"

TMP="$(mktemp -d)"
trap "rm -rf $TMP" EXIT

setup_apt "$TMP" "$MIRROR" "$DISTRO" "$COMPONENT"
apt-get -c "$TMP/apt.conf" update
apt-get -c "$TMP/apt.conf" source "$PACKAGE"
#apt-config -c $TMP/apt.conf dump




